### ISSUE TITLE
visualising node labels- is it random?

### ISSUE THREAD

**Issue by laurieresearch** [medialab/minivan#54]
This might be more of a clarification than an issue.

When interacting with the networks in the main navigation window it’s not clear (to me at least) why the labels of some nodes appear and not others. Zooming in and out causes labels to both appear and disappear. The appearance/disappearance of the labels doesn’t seem obviously related to any of the node attributes. Is it random?

Thanks
Laurie

**Comment by Yomguithereal** [comment]
Hello @laurieresearch. The apparition of label is not random. The labels are chosen based upon: 1. the size of the nodes (larger nodes have more chance to be selected) then 2. a grid constraint that tries to only keep one label per cell, then 3. some basic anticollision and finally 4. we try to keep some state from camera move to camera move to try and lessen user disorientation (but maybe we failed at it :) ). The selection of labels to display is an open problem and there is no silver bullet. The grid can be tweaked but the option is not yet exposed through minivan.

If you want a more precise understanding of the label selection the related code can be found [here](https://github.com/jacomyal/sigma.js/blob/v2/src/heuristics/labels.ts).

**Comment by laurieresearch** [comment]
Thank you for clarifying @Yomguithereal - this is a very helpful summary
